### ISSUE TITLE
登录不了

### ISSUE THREAD

**Issue by cenxuebin** [qwqjsq/qwqjsq#1]
https://www.qwqjsq6.com/auth/login页面 无法登录

**Comment by fuyelk** [comment]
这个地址在墙外，可以登录的

**Comment by cenxuebin** [comment]
我更换过微软和谷歌的DNS都还是不行

主页时不时可以打开，登录页面一直打不开


[cid:image003.jpg@01D59624.9E59C510]

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Xiong Jian<mailto:notifications@github.com>
发送时间: 2019年11月8日 9:57
收件人: qwqjsq/qwqjsq<mailto:qwqjsq@noreply.github.com>
抄送: cenxuebin<mailto:cenxuebin@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [qwqjsq/qwqjsq] 登录不了 (#1)


这个地址在墙外，可以登录的

―

**Comment by qwqjsq** [comment]
網站服務器問題，現在已經修復了
