### ISSUE TITLE
收不到邮箱验证

### ISSUE THREAD

**Issue by starrysky12138** [qwqjsq/qwqjsq#3]

**Comment by d393911462** [comment]
ok




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"starrysky12138"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月26日(星期二) 中午12:19
收件人:&nbsp;"qwqjsq/qwqjsq"<qwqjsq@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[qwqjsq/qwqjsq] 收不到邮箱验证 (#3)

**Comment by starrysky12138** [comment]
注册账号时，一直收不到验证的邮件

At 2019-11-26 16:31:50, "d393911462" <notifications@github.com> wrote:
ok




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"starrysky12138"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月26日(星期二) 中午12:19
收件人:&nbsp;"qwqjsq/qwqjsq"<qwqjsq@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[qwqjsq/qwqjsq] 收不到邮箱验证 (#3)
